interface Env {
  AUTH_RATE_LIMITER: RateLimit
  API_RATE_LIMITER: RateLimit

  FIREBASE_PROJECT_ID: string
  FIREBASE_ADMIN_SERVICE_ACCOUNT_KEY: string
  SESSION_SECRET: string

  VITE_FIREBASE_API_KEY: string
  VITE_FIREBASE_AUTH_DOMAIN: string
  VITE_FIREBASE_PROJECT_ID: string
  VITE_APP_URL: string
}
